// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "879a0187-044a-4b69-b9ae-ee66c7438d23");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1656255826);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1656256186);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1656256066);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1656255946);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1656255856);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 44945);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1656255795);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ae50963d-d42b-4d79-82ef-906c88f4c9ac}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"webcompat-reporter_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1656255860037");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1656257643037");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1656255811618");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1656277411618");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1656255809");
user_pref("browser.slowStartup.averageTime", 6484);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210325192444");
user_pref("browser.startup.homepage_override.mstone", "78.9.0");
user_pref("browser.startup.lastColdStartupCheck", 1656255800);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.iniFile.exists.appversion", "78.9.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.redhat.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "4a1ed776d29d4be9b7dd9c62baed57f9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.9.0");
user_pref("extensions.lastPlatformVersion", "78.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"eefaf7cb-6005-4c95-b74a-f97f74c445ae\",\"formautofill@mozilla.org\":\"3a2539c2-0765-45da-bb15-69535cf9818d\",\"screenshots@mozilla.org\":\"84b65175-d4a1-4961-b011-e6fbf49575ef\",\"webcompat-reporter@mozilla.org\":\"068a0850-594d-4230-b32a-ae051bb6ac8c\",\"webcompat@mozilla.org\":\"28318b08-9021-48fe-af14-ebd287ad60d0\",\"default-theme@mozilla.org\":\"b4ec48d3-5238-4f4d-a7ac-71d77426ca87\",\"google@search.mozilla.org\":\"406d4227-9948-4630-a038-161f18c0f22e\",\"amazondotcom@search.mozilla.org\":\"94dbd801-125d-4739-a7bf-86e5345a3ba0\",\"wikipedia@search.mozilla.org\":\"577d23fa-72bc-466f-be7e-801d08fc692f\",\"bing@search.mozilla.org\":\"94a21191-b30c-4a18-b4a6-d337bd178e45\",\"ddg@search.mozilla.org\":\"1ae822da-70b1-4c68-bbbb-5763e7a132fc\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1656256213);
user_pref("media.gmp-manager.buildID", "20210325192444");
user_pref("media.gmp-manager.lastCheck", 1656255865);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1656256213);
user_pref("places.history.expiration.transient_current_max_pages", 107280);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1656255865);
user_pref("security.remote_settings.intermediates.checked", 1656255865);
user_pref("security.sandbox.content.tempDirSuffix", "e2de46d4-2e09-43e2-8bd2-bf4df6f40069");
user_pref("security.sandbox.plugin.tempDirSuffix", "fb78a4c8-0b2b-4167-86eb-eb37065808f8");
user_pref("services.blocklist.addons-mlbf.checked", 1656255865);
user_pref("services.blocklist.gfx.checked", 1656255865);
user_pref("services.blocklist.plugins.checked", 1656255865);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1656248234851\"");
user_pref("services.settings.last_update_seconds", 1656255865);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1656255865);
user_pref("services.settings.main.cfr.last_check", 1656255865);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1656255865);
user_pref("services.settings.main.hijack-blocklists.last_check", 1656255865);
user_pref("services.settings.main.language-dictionaries.last_check", 1656255865);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1656255865);
user_pref("services.settings.main.public-suffix-list.last_check", 1656255865);
user_pref("services.settings.main.search-config.last_check", 1656255865);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1656255865);
user_pref("services.settings.main.sites-classification.last_check", 1656255865);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1656255865);
user_pref("services.settings.main.whats-new-panel.last_check", 1656255865);
user_pref("services.settings.security.onecrl.checked", 1656255865);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1656256213);
user_pref("toolkit.startup.last_success", 1656255793);
user_pref("toolkit.telemetry.cachedClientID", "0c568a1d-7c39-406f-94d4-e7af44d910d8");
user_pref("toolkit.telemetry.previousBuildID", "20210325192444");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
